name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      working-directory: ${{github.workspace}}
      run: ./make.ps1
      shell: pwsh

    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/install/*
