name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-14, ubuntu-latest, windows-latest ]

    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Build
      working-directory: ${{github.workspace}}
      run: ./make.ps1
      shell: pwsh

    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.os}}
        path: ${{github.workspace}}/install/*
